name: Build latest OS and EE image

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Checkout clair-scanner
        uses: actions/checkout@v2
        with:
          repository: arminc/clair-scanner
          path: clair-scanner

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: v0.4.1
          qemu-version: 4.2.0-7

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build/Push OSS image
        run: |
          docker buildx build --push \
            --tag hazelcast/hazelcast:latest \
            --platform=linux/arm64,linux/amd64,linux/ppc64le,linux/s390x hazelcast-oss
      - name: Build/Push EE image
        run: |
          docker buildx build --push \
            --tag hazelcast/hazelcast-enterprise:latest \
            --platform=linux/arm64,linux/amd64,linux/ppc64le,linux/s390x hazelcast-enterprise

      - name: Scan Hazelcast image by Azure (Trivy + Dockle)
        uses: Azure/container-scan@v0
        with:
          image-name: hazelcast/hazelcast:latest
      - name: Scan Hazelcast image by Anchore
        uses: anchore/scan-action@v1
        with:
          image-reference: hazelcast/hazelcast:latest
      - name: Scan Hazelcast Enterprise image by Azure (Trivy + Dockle)
        uses: Azure/container-scan@v0
        with:
          image-name: hazelcast/hazelcast-enterprise:latest
      - name: Scan Hazelcast Enterprise image by Anchore
        uses: anchore/scan-action@v1
        with:
          image-reference: hazelcast/hazelcast-enterprise:latest
      - name: Scan Hazelcast OS and Enterprise images by Clair
        run: |
          sh .github/scripts/clair_vulnerability_scan.sh \
            hazelcast/hazelcast:latest \
            hazelcast/hazelcast-enterprise:latest