name: Build latest OS and EE image

on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name:  Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.1.1
        with:
          version: v0.5.1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build/Push OSS image
        run: |
          docker buildx build --push \
            --tag hazelcast/hazelcast:latest \
            --platform=linux/arm64,linux/amd64,linux/ppc64le,linux/s390x hazelcast-oss
      - name: Build/Push EE image
        run: |
          docker buildx build --push \
            --tag hazelcast/hazelcast-enterprise:latest \
            --platform=linux/arm64,linux/amd64,linux/ppc64le,linux/s390x hazelcast-enterprise
  scan:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Pull docker images
        run: |
          docker pull hazelcast/hazelcast:latest
          docker pull hazelcast/hazelcast-enterprise:latest
          docker images --digests
      - name: Scan Hazelcast image by Azure (Trivy + Dockle)
        if: always()
        uses: Azure/container-scan@v0
        with:
          image-name: hazelcast/hazelcast:latest
      - name: Scan Hazelcast image by Anchore
        if: always()
        uses: anchore/scan-action@v2.0.2
        with:
          image: hazelcast/hazelcast:latest
          fail-build: true
      - name: Scan Hazelcast image by Snyk
        if: always()
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: hazelcast/hazelcast:latest
          args: --file=hazelcast-oss/Dockerfile --policy-path=.github/containerscan
      - name: Scan Hazelcast Enterprise image by Azure (Trivy + Dockle)
        if: always()
        uses: Azure/container-scan@v0
        with:
          image-name: hazelcast/hazelcast-enterprise:latest
      - name: Scan Hazelcast Enterprise image by Anchore
        if: always()
        uses: anchore/scan-action@v2.0.2
        with:
          image: hazelcast/hazelcast-enterprise:latest
          fail-build: true
      - name: Scan Hazelcast Enterprise image by Snyk
        if: always()
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: hazelcast/hazelcast-enterprise:latest
          args: --file=hazelcast-enterprise/Dockerfile --policy-path=.github/containerscan

