name: Scheduled Vulnerability Scans

on:
    schedule:
        - cron: '0 2 * * *'

jobs:
    trigger-vulnerability-scan-5_2_z:
        uses: ./.github/workflows/vulnerability_scan_subworkflow.yml
        with:
            ref: 5.2.z
    trigger-vulnerability-scan-5_1_z:
        uses: ./.github/workflows/vulnerability_scan_subworkflow.yml
        with:
            ref: 5.1.z
    trigger-vulnerability-scan-5_0_z:
        uses: ./.github/workflows/vulnerability_scan_subworkflow.yml
        with:
            ref: 5.0.z